export function list(): Promise<Product[]> {
  const data = [
    {
      id: 325,
      idx: '533c145f-a8e4-4f7e-b31c-222971157750',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-14T01:44:25.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '지미 그린호프 싸인 포토',
      nameEn: 'JIMMY GREENHOFF SIGNED PHOTO',
      nameCn: 'JIMMY GREENHOFF SIGNED PHOTO',
      nameJp: 'JIMMY GREENHOFF SIGNED PHOTO',
      detailName: 'JIMMY GREENHOFF SIGNED PHOTO',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 지미 그린호프 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> JIMMY GREENHOF\bF</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 203*304</p><p><strong>- STARTING PRICE:</strong> 10,000 WON</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>지미 그린호프는 1946년생 잉글랜드 공격수이다. 스킬이 좋은 공격수로 리그 경기를 거의 600경기 가까이 출전했으며, 76-77시즌 맨체스터 유나이티드의 FA컵 우승 당시 주전 멤버였으며 시즌 34경기 12골을 기록했다. 해당 시즌은 포포투가 선정한 맨유 역대 최강팀 10위에 이름을 올렸다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 10000,
      priceEn: 7.55,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 20,
      wishCount: 0,
      imageName: 'b44d0e87-532a-4425-8e82-da5934c70db2.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-15T11:00:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 326,
      idx: '0af5b5dd-4e5e-4f0b-8235-815e9ed6440f',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-14T01:46:33.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '아서 앨비스턴 싸인 포토',
      nameEn: 'ARTHUR ALBISTON SIGNED PHOTO',
      nameCn: 'ARTHUR ALBISTON SIGNED PHOTO',
      nameJp: 'ARTHUR ALBISTON SIGNED PHOTO',
      detailName: 'ARTHUR ALBISTON SIGNED PHOTO',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 아서 앨비스턴 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> ARTHUR ALBISTON</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 203*304</p><p><strong>- STARTING PRICE:</strong> 10,000 WON</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>아서 앨비스턴은 1957년생 스코틀랜드 레프트백이다. 맨체스터 유나이티드 유스 출신으로 1974년 1군에 데뷔 후 무려 485경기를 출전한 레전드다. FA컵 우승만 총 3번(76-77, 82-83, 84-85)으로 당시 클럽 신기록을 달성하기도 했다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 10000,
      priceEn: 7.55,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 20,
      wishCount: 0,
      imageName: '1c021d48-07bd-47de-9359-1aac5fa29ec7.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-15T11:00:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 328,
      idx: '7dce6c02-0b75-44a1-96fa-d4d5e3c45d1b',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-14T01:57:32.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '폴 스콜스 싸인 포토 (09-10 맨시티전 헤더 골)',
      nameEn: 'PAUL SCHOLES SIGNED PHOTO',
      nameCn: 'PAUL SCHOLES SIGNED PHOTO',
      nameJp: 'PAUL SCHOLES SIGNED PHOTO',
      detailName: 'PAUL SCHOLES SIGNED PHOTO (09-10 HEADER GOAL VS MAN C)',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 폴 스콜스 싸인 포토 (09-10 맨시티전 헤더 골)\n</pre><p><strong>- AUTOGRAPH:</strong> PAUL SCHOLES</p><p><strong>- TYPE:</strong> SIGNED PHOTO: 17 APR 2010(EPL)&nbsp;vs MANCHESTER CITY</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 304*203</p><p><strong>- STARTING PRICE:</strong> 30,000 WON</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'생강 왕자\' 폴 스콜스는 1974년생 잉글랭드 미드필더로 맨체스터 유나이티드 원 클럽 맨이다.</p><p><br></p><p>퍼거슨의 아이들 중 하나로 천재적인 미드필드였던 그는 총 718경기를 출전한 레전드로 총 11번의 리그 우승과 FA컵 3회, 챔피언스 리그 2회를 포함해 수도 없이 많은 우승 트로피를 들어 올렸으며, 98-99트레블의 주역이기도 하다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 30000,
      priceEn: 22.66,
      originPrice: 30000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 20,
      wishCount: 0,
      imageName: 'baaa821a-3f5f-4b19-880e-4733db017788.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-15T11:00:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 330,
      idx: '5f8edc5a-06b2-43e6-887d-41d8b7702da1',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-14T02:09:40.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '크리스티아누 호날두 싸인 포토',
      nameEn: 'CRISTIANO RONALDO SIGNED PHOTO',
      nameCn: 'CRISTIANO RONALDO SIGNED PHOTO',
      nameJp: 'CRISTIANO RONALDO SIGNED PHOTO',
      detailName: 'CRISTIANO RONALDO SIGNED PHOTO',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 크리스티아누 호날두 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> CRISTIANO RONALDO SIGNED PHOTO</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING DATE: </strong>14 NOV 2021</p><p><strong>- SIGNING LOCATION:</strong> LISBON</p><p><strong>- SIZE(mm):</strong> 403*304</p><p><strong>- STARTING PRICE:</strong> 400,000 WON</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>크리스티아누 호날두는 1985년생 포르투갈의 윙어이자 공격수로 현재는 사우디의 알 나스르에서 활약 중이다.</p><p><br></p><p>포르투갈 마데이라 제도에서 태어난 호날두는 스포르팅 CP에서 데뷔해 맨체스터 유나이티드에서 꽃을 피우고 레알 마드리드에서 만개하였다. 이 후 유벤투스, 맨유를 거쳐 사우디의 알 나스르로 이적하여 사우디 붐의 시작이 되었다.</p><p><br></p><p>챔피언스리그의 남자라는 별명처럼 챔스 통산 최다 출전, 골, 어시스트, 득점왕, 한 시즌 최다 골 등등 엄청난 기록들을 가지고 있으며 최근 A매치에서도 200경기라는 역대 최다 기록을 세웠으며, 123골 또한 A매치 역대 최다 기록이다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 400000,
      priceEn: 302.11,
      originPrice: 400000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 20,
      wishCount: 0,
      imageName: '727b2af8-0816-4f4a-a6e7-46685be24d87.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-15T11:00:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 327,
      idx: '1fc43e1e-6aa3-44ab-9fbd-ae95144204d9',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-14T01:51:51.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '데니스 로 싸인 포토 (시그니처 골 셀레브레이션)',
      nameEn: 'DENIS LAW SIGNED PHOTO',
      nameCn: 'DENIS LAW SIGNED PHOTO',
      nameJp: 'DENIS LAW SIGNED PHOTO',
      detailName: 'DENIS LAW SIGNED PHOTO (SIGNATURE GOAL CELEBRATION)',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 데니스 로 싸인 포토 (시그니처 골 셀레브레이션)\n</pre><p><strong>- AUTOGRAPH:</strong> DENIS LAW</p><p><strong>- TYPE:</strong> SIGNED PHOTO:&nbsp;SIGNATURE GOAL CELEBRATION</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 304*203</p><p><strong>- STARTING PRICE:</strong> 30,000 WON</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'KING Denis\' 데니스 로는 1940년생 스코틀랜드 공격수로 명실상부 맨체스터 유나이티드의 레전드이다. 맨유의 홈경기장 올드 트래포드(OT)에는 바비 찰튼, 조지 베스트와 함께 그의 동상이 세워져있으며 스코틀랜드 유일한 발롱도르(1964년) 위너이다.</p><p><br></p><p>뮌헨 참사로 인해 어려움에 있던 맨체스터 유나이티드를 재건한 핵심 선수로써 바비 찰튼, 조지 베스트와 전설적인 트리오를 형성하여 63-64 시즌 준우승과 함께 42경기 46골로 발롱도르를 수상했고, 이 후 버스비의 아이들은 67-68 유로피언 컵(UCL 전신)을 우승하여 전설이 되었다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 30000,
      priceEn: 22.66,
      originPrice: 30000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 20,
      wishCount: 0,
      imageName: '224079ed-8f78-4933-9a8d-e78e992d9107.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-15T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 329,
      idx: 'a2ada941-003e-48a4-931a-1bd723c4091f',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-14T02:04:50.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '폴 스콜스 싸인 포토 (07-08 챔스 우승 셀레브레이션)',
      nameEn: 'PAUL SCHOLES SIGNED PHOTO',
      nameCn: 'PAUL SCHOLES SIGNED PHOTO',
      nameJp: 'PAUL SCHOLES SIGNED PHOTO',
      detailName: 'PAUL SCHOLES SIGNED PHOTO (07-08 UCL WINNING CELEBRATION)',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 폴 스콜스 싸인 포토 (07-08 챔스 우승 셀레브레이션)\n</pre><p><strong>- AUTOGRAPH:</strong> PAUL SCHOLES</p><p><strong>- TYPE:</strong> SIGNED PHOTO: 21 MAY 2008 MOSCOW(UCL FINAL) vs CHELSEA</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 203*304</p><p><strong>- STARTING PRICE:</strong> 30,000 WON</p><p><br></p><p><span style="color: rgb(0, 0, 0); font-size: 14px;">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'생강 왕자\' 폴 스콜스는 1974년생 잉글랭드 미드필더로 맨체스터 유나이티드 원 클럽 맨이다.</p><p><br></p><p>퍼거슨의 아이들 중 하나로 천재적인 미드필드였던 그는 총 718경기를 출전한 레전드로 총 11번의 리그 우승과 FA컵 3회, 챔피언스 리그 2회를 포함해 수도 없이 많은 우승 트로피를 들어 올렸으며, 98-99트레블의 주역이기도 하다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 30000,
      priceEn: 22.66,
      originPrice: 30000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 20,
      wishCount: 0,
      imageName: '9a6e7ef7-f70d-42d7-9203-8c177836b45d.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:01.000Z',
      deadLineTime: '2023-08-15T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 424,
      idx: '87e33cdc-151f-4d43-a548-b0857e0abbc3',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-16T12:54:38.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '한국이름',
      nameEn: '영어이름',
      nameCn: '중국어이름',
      nameJp: '일본이름',
      detailName: '상세이름',
      contents: '<p>기본설명을 입력</p>',
      price: 1000,
      priceEn: 0.76,
      originPrice: 1000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 10,
      subCategory: 15,
      wishCount: 0,
      imageName: 'a6eab7d0-14e7-4bea-899c-61a430f17086.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: '123',
      startTime: '2023-08-16T12:52:49.000Z',
      deadLineTime: '2023-08-16T12:52:51.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 402,
      idx: '21d37f2a-779c-45e5-a9f8-d9bb7f8c8f78',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-04T02:24:08.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '오타니 경기 실착 유니폼',
      nameEn: 'OHTANI GAME-USED JERSEY',
      nameCn: 'OHTANI GAME-USED JERSEY',
      nameJp: 'OHTANI GAME-USED JERSEY',
      detailName: 'LOS ANGELES ANGELS vs SEATTLE MARINERS - 13 JUL 2019 ',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 19.07.13(ANGEL STADIUM) LA 에인절스 vs 시애틀 매리너스 경기 실착 유니폼.\n</pre><p><strong>- Player:</strong> SHOHEI OHTANI</p><p><strong>- TYPE: </strong>Game-used LA Angels Home Jersey</p><p><strong>- SIZE:</strong> 48</p><p><strong>- FEATURE:</strong> 13 JUL 2019 Major League Baseball vs Seattle Mariners</p><p><strong>- STARTING PRICE:</strong> 90,000,000 WON</p><p><br></p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube.com/embed/EqA99MqUGi0?showinfo=0"></iframe><p><br></p><p><br></p><p><strong style="font-size: 20px;">DESCRIPTION</strong></p><p><br></p><p>오타니 쇼헤이는 1994년생 일본의 프로 야구 선수이다. 현재 메이저 리그 로스앤젤레스 에인절스 오브 애너하임의 소속으로, 투수와 타자를 모두 겸하는 Two-Way Player, 일명 \'투타겸업\'을 하고 있다.</p><p><br></p><p>2013년 일본프로야구에서 투타겸업으로 프로 커리어를 시작했으면, 2016년 일본시리즈 우승과 MVP를 차지했다. 그 후 2018년 로스앤젤레스 에인절스로 이적하여 MLB로 입성하였고, 첫 해 \'신인왕\' 수상 후 2021년 만장일치 \'아메리칸 리그 MVP\', 2022년 베이브 루스 이후 104년만의 \'10승-10홈런\'와 MLB 역사상 최초 \'15승-30홈런\' 등의 대기록을 달성했다.</p><p><br></p><p>현존하는 최고의 아시아 스포츠 스타이자, 메이저 리그와 지구상에서 가장 핫한 선수이다.</p><p><br></p><h2><strong>FRAMING</strong></h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 90000000,
      priceEn: 67975.8,
      originPrice: 100000000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 47,
      subCategory: 49,
      wishCount: 0,
      imageName: '90643b73-a5e4-457d-a1a7-54d9bf059397.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-18T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 409,
      idx: 'fef8fc50-5424-4777-ad38-15807a0f17ce',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-08T08:47:32.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '나성범 매치원 유니폼',
      nameEn: 'Na Sung-bum Matchworn Jersey',
      nameCn: 'Na Sung-bum Matchworn Jersey',
      nameJp: 'Na Sung-bum Matchworn Jersey',
      detailName: 'NC 다이노스 vs SK 와이번스 -17.06.21',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 17.06.21 NC vs SK, 나성범(2타수 2안타 1홈런) 싸인 매치원 유니폼.\n</pre><p>- AUTOGRAPH: NA SUNG-BUM</p><p>- TYPE: MatchWorn Signed NC Dinos Shirt: 21 JUN 2017 vs SK Wyverns</p><p>- SIGNING LOCATION: PRIVATE</p><p>- SIZE: UNMARKED</p><p>- 시작가: 350,000</p><p><br></p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><h2>PHOTO MATCH</h2><p><br></p><p><img src="https://image.collexx.io/f45e8284-ebda-4d52-8168-eea68331cdad.png"></p><p><br></p><h2>Description</h2><p><br></p><p>매년 3할 타율과 150안타 이상을 보장하고 20홈런 이상과 5할 이상의 장타율을 꾸준히 기록하는 강타자 나성범. 1군 데뷔 2년차인 2014년에 3할 30홈런 100타점을 기록해 외야수 부문 골든글러브를 거머쥐었을 정도로 리그 정상급 타자로 빠르게 성장했다.</p><p>엄청난 체격과 팔근육에서 나오는 파워와 무게 중심을 뒤에 두며 강한 하체에서 나오는 원심력을 이용한 힙 턴을 통해 빠른 배트 스피드를 만들어내는 타자다. 흔희 \'팔뚝\'이라고 부르는 전완근이 매우 크고 두꺼운데다 손도 커서 여간해서는 상대의 공에 배트가 밀리지 않으며, 타이밍만 잘 맞추면 무조건 홈런을 치는 힘을 가지고 있다.</p><p>해당 상품은 2017년 6월 21일 SK 와이번스와의 경기에서 입었던 매치원 유니폼이다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 350000,
      priceEn: 264.35,
      originPrice: 350000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 1,
      category: 47,
      subCategory: 48,
      wishCount: 0,
      imageName: '26ca9396-412c-4ec5-a1d0-059d8cb24f73.png',
      status: 'ONSALE',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-22T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 316,
      idx: '80162869-cfd9-4091-8330-5129bb18ef7e',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:24:49.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '김문환 싸인 포토',
      nameEn: 'KIM MOON-HWAN SIGNED PHOTO',
      nameCn: 'KIM MOON-HWAN SIGNED PHOTO',
      nameJp: 'KIM MOON-HWAN SIGNED PHOTO',
      detailName: '김문환 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 김문환 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> KIM MOON-HWAN</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 152*102</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'무나니\' 김문환은 1995년생 대한민국의 라이트백으로 현재 K리그 전북 현대에서 활약하고 있다.</p><p><br></p><p>2017년 부산 아이파크에서 데뷔하여 로스앤젤리스 FC를 거쳐 전북에 합류한 대한민국 라이트백의 현재이자 미래이다. 2018 자카르타,팔렘방 아시안 게임, 2019 아랍에미리트 아시안컵, 2022 카타르 월드컵까지 꾸준히 대한민국의 오른쪽 수비로 활약했으며, 현재는 국가대표의 붙박이 라이트백으로 자리매김했다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 40000,
      priceEn: 30.21,
      originPrice: 1,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 23,
      wishCount: 0,
      imageName: '66b91308-a664-4ad3-8dfa-6a882fa7317b.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTKMH00ID',
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-11T11:29:21.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 322,
      idx: '29c64e67-edd3-41d8-a50f-74c1956a3bcf',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:31:38.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '황인범 싸인 포토',
      nameEn: 'HWANG IN-BEOM SIGNED PHOTO',
      nameCn: 'HWANG IN-BEOM SIGNED PHOTO',
      nameJp: 'HWANG IN-BEOM SIGNED PHOTO',
      detailName: '황인범 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 황인범 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> HWANG IN-BEOM</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 151*101</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><h2><br></h2><h2>Description</h2><p><br></p><p>황인범은 1996년생 대한민국의 미드필더로 \b2015년 대전 시티즌에서 데뷔하여 현재는 올림피아코스에서 뛰고 있다.</p><p><br></p><p>국가대표 주전 미드필더로 2018년 아시안 게임 금메달, 2022년 카타르 월드컵 16강 등의 업적에 혁혁한 공을 세운 대한민국 축구의 미래이자 현재이다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 40000,
      priceEn: 30.21,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 23,
      wishCount: 0,
      imageName: 'c8398906-3b64-4a05-91c0-12376d3e2ec2.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTHIB254T',
      startTime: '2023-08-03T15:00:01.000Z',
      deadLineTime: '2023-08-11T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 320,
      idx: '2824a6bf-1f3f-4d49-8e86-73274277f0dc',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:29:00.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '이청용 싸인 포토',
      nameEn: 'LEE CHUNG-YONG SIGNED PHOTO',
      nameCn: 'LEE CHUNG-YONG SIGNED PHOTO',
      nameJp: 'LEE CHUNG-YONG SIGNED PHOTO',
      detailName: '이청용 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 이청용 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> LEE CHUNG-YONG</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 152*102</p><p><br></p><p><span style="color: rgb(0, 0, 0); font-size: 14px;">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'블루 드래곤\' 이청용은 1988년생 대한민국의 공격형 미드필더이자 윙어로 현재 K리그 울산 현대에서 활약하고 있다.</p><p><br></p><p>2004년 FC 서울에서 데뷔한 이청용은 2009년 EPL 볼튼 원더러스로 이적해 10년 넘게 유럽무대를 누비다 2020년 울산 현대로 국내 무대에 복귀하였다. 국가대표로 89경기에 출전하였으며 2010년 남아공 월드컵, 2014년 브라질 월드컵에 주축멤버로 대한민국을 빛냈다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 20000,
      priceEn: 15.11,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 18,
      wishCount: 0,
      imageName: '543904a1-aa68-4d21-9371-e037ade7fccb.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTLCY6KCI',
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-11T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 319,
      idx: '4ac7302d-9816-44f3-9c12-9580943e305f',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:27:55.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '조영욱 싸인 포토',
      nameEn: 'CHO YOUNG-WOOK SIGNED PHOTO',
      nameCn: 'CHO YOUNG-WOOK SIGNED PHOTO',
      nameJp: 'CHO YOUNG-WOOK SIGNED PHOTO',
      detailName: '조영욱 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 조영욱 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> CHO YOUNG-WOOK</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 147*100</p><p><br></p><p><span style="color: rgb(0, 0, 0); font-size: 14px;">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'슈팅 몬스터\' \b조영욱은 1999년생 대한민국의 공격수로 현재 K리그 FC 서울 소속으로 김천 상무에서 군 복무 중이다.</p><p><br></p><p>2018년 데뷔 후 FC 서울에서만 쭉 활약한 원 클럽 맨으로 연령별 대표팀부터 꾸준한 관심을 받아온 조영욱은 다가오는 항저우 아시안 게임에도 최종 승선하며 기대를 모으고 있다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 10000,
      priceEn: 7.55,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 23,
      wishCount: 0,
      imageName: '7c629ef0-7c84-46ec-b2ae-79c3392b89ce.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTCYW3QOB',
      startTime: '2023-08-03T15:00:01.000Z',
      deadLineTime: '2023-08-11T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 318,
      idx: 'c0cd6176-dca5-4955-9bad-8da69873b2a1',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:26:49.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '김태환 싸인 포토',
      nameEn: 'KIM TAE-HWAN SIGNED PHOTO',
      nameCn: 'KIM TAE-HWAN SIGNED PHOTO',
      nameJp: 'KIM TAE-HWAN SIGNED PHOTO',
      detailName: '김태환 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 김태환 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH: </strong>KIM TAE-HWAN</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 152*102</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'치타\' 김태환은 1989년생 대한민국의 라이트백으로 현재 K리그 울산 현대에서 활약하고 있다.</p><p><br></p><p>2010년 FC 서울에서 데뷔한 김태환은 성남을 거쳐 2015년 울산 현대에 입단했다. 주로 윙어로 뛰던 김태환은 2019년 즈음 라이트백으로 완전히 포지션 변경을 한 후 두각을 나타냈고 국대에도 자주 승선하며 2022년 카타르 월드컵 최종 명단에도 이름을 올리게 되었다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 10000,
      priceEn: 7.55,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 23,
      wishCount: 0,
      imageName: '4d5d220e-0877-4240-9a45-ad49c64af7b4.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTKTH6FS3',
      startTime: '2023-08-03T15:00:01.000Z',
      deadLineTime: '2023-08-11T11:00:01.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 323,
      idx: 'f4a1dcd1-6955-422f-9583-951123fdc05f',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:32:33.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '엄원상 싸인 포토',
      nameEn: 'UM WON-SANG SIGNED PHOTO',
      nameCn: 'UM WON-SANG SIGNED PHOTO',
      nameJp: 'UM WON-SANG SIGNED PHOTO',
      detailName: '엄원상 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 엄원상 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> UM WON-SANG</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 152*102</p><p><br></p><p><span style="font-size: 14px; color: rgb(0, 0, 0);">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'엄살라\' 엄원상은 1999년생 대한민국의 윙어로 현재 K리그 울산 현대에서 활약하고 있다.</p><p><br></p><p>2019년 광주 FC에서 데뷔한 후 울산으로 이적해 빠른발을 활용해 울산의 17년만의 우승을 도왔으며 다가오는 항저우 아시안 게임에도 최종 승선하였다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 20000,
      priceEn: 15.11,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 23,
      wishCount: 0,
      imageName: '0b98053a-6fc0-4f6d-bed9-471e4892d49f.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTUWS2EMD',
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-11T11:00:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 317,
      idx: '69c32430-112a-407f-adc8-7e4bc749b3e9',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-07-13T05:25:54.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '송민규 싸인 포토',
      nameEn: 'SONG MIN-KYU SIGNED PHOTO',
      nameCn: 'SONG MIN-KYU SIGNED PHOTO',
      nameJp: 'SONG MIN-KYU SIGNED PHOTO',
      detailName: '송민규 싸인 포토',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 송민규 선수 싸인 포토\n</pre><p><strong>- AUTOGRAPH:</strong> SONG MIN-KYU</p><p><strong>- TYPE:</strong> SIGNED PHOTO</p><p><strong>- SIGNING LOCATION:</strong> PRIVATE</p><p><strong>- SIZE(mm):</strong> 152*102</p><p><br></p><p><span style="color: rgb(0, 0, 0); font-size: 14px;">* 액자 미포함 상품으로 액자 옵션 선택 가능.</span></p><p><span style="font-size: 14px;">*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 물품에 마모, 오염, 스크레치 등의 컨디션 이슈가 있을 수 있음. 사진을 통해 확인 가능하며, 그로 인한 응찰 취소는 허용되지 않음.</span></p><p><span style="font-size: 14px;">﻿*</span><span style="font-size: 14px; color: rgb(0, 0, 0);"> 전화 예약 (02-548-8815) 통해서 실물 확인 가능.</span></p><p><br></p><h2>Description</h2><p><br></p><p>\'송스타\' 송민규는 1999년생 대한민국의 윙어로 현재 K리그 전북 현대에서 활약하고 있다.</p><p><br></p><p>2018년 포항 스틸러스에서 데뷔하여 2021년 전북 현대로 이적하였고, 꾸준히 국가대표팀과 연령별 대표팀에 뽑히며 성장하고 있다. 2020 도쿄 올림픽, 2022 카타르 월드컵 최종 명단에 이름을 올렸고, 다가오는 항저우 아시안 게임 최종 명단에도 선발되었다.</p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 60000,
      priceEn: 45.32,
      originPrice: 10000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 10,
      subCategory: 23,
      wishCount: 0,
      imageName: '9fa1ce00-0d50-498d-bad4-778c917c53e7.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'N',
      failCode: 'NO',
      serialNumber: 'CXPV23PTSMK4G8B',
      startTime: '2023-08-03T15:00:01.000Z',
      deadLineTime: '2023-08-11T11:00:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 388,
      idx: '5af8f950-7da5-46ce-9946-0928297b1b45',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-02T09:56:33.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '백승호 매치원 유니폼',
      nameEn: 'PAIK SEUNGHO MATCHWORN KIT',
      nameCn: 'PAIK SEUNGHO MATCHWORN KIT',
      nameJp: 'PAIK SEUNGHO MATCHWORN KIT',
      detailName: 'JEONBUK vs PSG - 03 AUG 2023',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 23.08.03(부산 아시아드 주경기장) 전북현대 vs 파리생제르맹 친필싸인 매치원 유니폼.\n</pre><p><strong>- AUTOGRAPH:</strong> PAIK SEUNGHO</p><p><strong>- TYPE: </strong>MatchWorn Signed Jeonbuk Hyundai Motors 2023 Home Special Match Kit</p><p><strong>- SIGNING DATE:</strong> 06 AUG 2023</p><p><strong>- SIGNING LOCATION: </strong>Jeonju, Korea</p><p><strong>- SIZE: </strong>M</p><p><strong>- FEATURE:</strong> 03 AUG 2023 Coupang Play Series vs Paris Saint-Germain</p><p><strong>- STARTING PRICE:</strong> 250,000 WON</p><p><br></p><p>* 사이즈는 유니폼에 기재된 사이즈이며, 일부 선수(백승호,이동준,한교원,최철순,문선민)는 신체에 맞춰 리폼 후 실착하였으니 참고하시기 바랍니다.</p><p>* 유니폼은 경기 후 구단에서 가볍게 세탁 후, 싸인 세션을 진행하였습니다.</p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><p><img src="https://image.collexx.io/ad3a96ff-b773-4545-8e71-9ad923c0fad2.gif"></p><p><br></p><h2>EVENT</h2><p class="ql-align-center"><a href="https://www.instagram.com/p/CvkJlshrmdN/" rel="noopener noreferrer" target="_blank" style="background-color: rgb(255, 255, 255);">이벤트 참여하기</a></p><p class="ql-align-center"><img src="https://image.collexx.io/f646c206-9ce5-4378-af21-c0bc1ef993f8.jpg"></p><p class="ql-align-center"><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다. <a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 2500000,
      priceEn: 1888.22,
      originPrice: 250000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 59,
      subCategory: 60,
      wishCount: 0,
      imageName: '649a721b-da54-4465-881e-93612bc8a379.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'Y',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-10T13:10:57.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 408,
      idx: '9760fe47-913b-412a-b1ab-708b634a38e0',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-08T08:23:50.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '송민규 매치이슈드 유니폼',
      nameEn: 'SONG MINKYU MATCH-ISSUED KIT',
      nameCn: 'SONG MINKYU MATCH-ISSUED KIT',
      nameJp: 'SONG MINKYU MATCH-ISSUED KIT',
      detailName: 'JEONBUK vs PSG - 03 AUG 2023',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 23.08.03(부산 아시아드 주경기장) 전북현대 vs 파리생제르맹 친필싸인 매치이슈드 유니폼.\n</pre><p><strong>- AUTOGRAPH:</strong> SONG MINKYU</p><p><strong>- TYPE: </strong>Match-Issued Signed Jeonbuk Hyundai Motors 2023 Home Special Match Kit</p><p><strong>- SIGNING DATE:</strong> 06 AUG 2023</p><p><strong>- SIGNING LOCATION: </strong>Jeonju, Korea</p><p><strong>- SIZE: </strong>M</p><p><strong>- FEATURE:</strong> 03 AUG 2023 Coupang Play Series vs Paris Saint-Germain</p><p><strong>- STARTING PRICE:</strong> 250,000 WON</p><p><br></p><p>* 사이즈는 유니폼에 기재된 사이즈이며, 일부 선수(백승호,이동준,한교원,최철순,문선민)는 신체에 맞춰 리폼 후 실착하였으니 참고하시기 바랍니다.</p><p>* 유니폼은 경기 후 구단에서 가볍게 세탁 후, 싸인 세션을 진행하였습니다.</p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><p><img src="https://image.collexx.io/1953615e-6e9b-40f6-8589-1b700614e183.gif"></p><p><br></p><h2>EVENT</h2><p class="ql-align-center"><a href="https://www.instagram.com/p/CvkJlshrmdN/" rel="noopener noreferrer" target="_blank" style="background-color: rgb(255, 255, 255);">이벤트 참여하기</a></p><p class="ql-align-center"><img src="https://image.collexx.io/f646c206-9ce5-4378-af21-c0bc1ef993f8.jpg"></p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다.<strong> </strong><a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 890000,
      priceEn: 672.21,
      originPrice: 250000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 59,
      subCategory: 60,
      wishCount: 0,
      imageName: '7395996c-623e-4d63-ae2a-16f1605f6bd2.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'Y',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-07T15:00:00.000Z',
      deadLineTime: '2023-08-10T12:07:48.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 383,
      idx: 'bdf505f0-1c06-4d13-aafe-f4c292a2c530',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-02T01:36:12.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '최철순 매치원 유니폼',
      nameEn: 'CHOI CHULSOON MATCHWORN KIT',
      nameCn: 'CHOI CHULSOON MATCHWORN KIT',
      nameJp: 'CHOI CHULSOON MATCHWORN KIT',
      detailName: 'JEONBUK vs PSG - 03 AUG 2023',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 23.08.03(부산 아시아드 주경기장) 전북현대 vs 파리생제르맹 친필싸인 매치원 유니폼.\n</pre><p><strong>- AUTOGRAPH:</strong> CHOI CHULSOON</p><p><strong>- TYPE: </strong>MatchWorn Signed Jeonbuk Hyundai Motors 2023 Home Special Match Kit</p><p><strong>- SIGNING DATE:</strong> 06 AUG 2023</p><p><strong>- SIGNING LOCATION: </strong>Jeonju, Korea</p><p><strong>- SIZE: </strong>M</p><p><strong>- FEATURE:</strong> 03 AUG 2023 Coupang Play Series vs Paris Saint-Germain</p><p><strong>- STARTING PRICE:</strong> 250,000 WON</p><p><br></p><p>* 사이즈는 유니폼에 기재된 사이즈이며, 일부 선수(백승호,이동준,한교원,최철순,문선민)는 신체에 맞춰 리폼 후 실착하였으니 참고하시기 바랍니다.</p><p>* 유니폼은 경기 후 구단에서 가볍게 세탁 후, 싸인 세션을 진행하였습니다.</p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><p><img src="https://image.collexx.io/8375321e-2f14-451f-b2fa-89b5192fa999.gif"></p><p><br></p><h2>EVENT</h2><p class="ql-align-center"><a href="https://www.instagram.com/p/CvkJlshrmdN/" rel="noopener noreferrer" target="_blank" style="background-color: rgb(255, 255, 255);">이벤트 참여하기</a></p><p class="ql-align-center"><img src="https://image.collexx.io/f646c206-9ce5-4378-af21-c0bc1ef993f8.jpg"></p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다.<strong> </strong><a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 1100000,
      priceEn: 830.82,
      originPrice: 250000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 59,
      subCategory: 60,
      wishCount: 0,
      imageName: '5945d96a-3514-4fb1-8a29-9ecaeabbda72.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'Y',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-10T11:56:23.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 384,
      idx: 'ebe06dd0-92c6-4049-a456-55cdce8176f8',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-02T01:36:36.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '박진섭 매치원 유니폼',
      nameEn: 'PARK JINSEOB MATCHWORN KIT',
      nameCn: 'PARK JINSEOB MATCHWORN KIT',
      nameJp: 'PARK JINSEOB MATCHWORN KIT',
      detailName: 'JEONBUK vs PSG - 03 AUG 2023',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 23.08.03(부산 아시아드 주경기장) 전북현대 vs 파리생제르맹 친필싸인 매치원 유니폼.\n</pre><p><strong>- AUTOGRAPH:</strong> PARK JINSEOB</p><p><strong>- TYPE: </strong>MatchWorn Signed Jeonbuk Hyundai Motors 2023 Home Special Match Kit</p><p><strong>- SIGNING DATE:</strong> 06 AUG 2023</p><p><strong>- SIGNING LOCATION: </strong>Jeonju, Korea</p><p><strong>- SIZE: </strong>L</p><p><strong>- FEATURE:</strong> 03 AUG 2023 Coupang Play Series vs Paris Saint-Germain</p><p><strong>- STARTING PRICE:</strong> 250,000 WON</p><p><br></p><p>* 사이즈는 유니폼에 기재된 사이즈이며, 일부 선수(백승호,이동준,한교원,최철순,문선민)는 신체에 맞춰 리폼 후 실착하였으니 참고하시기 바랍니다.</p><p>* 유니폼은 경기 후 구단에서 가볍게 세탁 후, 싸인 세션을 진행하였습니다.</p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><p><img src="https://image.collexx.io/9fd13b69-cefa-4fe6-b53d-20cf8f8f6fbe.gif"></p><p><br></p><h2>EVENT</h2><p class="ql-align-center"><a href="https://www.instagram.com/p/CvkJlshrmdN/" rel="noopener noreferrer" target="_blank" style="background-color: rgb(255, 255, 255);">이벤트 참여하기</a></p><p class="ql-align-center"><img src="https://image.collexx.io/f646c206-9ce5-4378-af21-c0bc1ef993f8.jpg"></p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다.<strong> </strong><a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 1300000,
      priceEn: 981.87,
      originPrice: 250000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 59,
      subCategory: 60,
      wishCount: 0,
      imageName: '92938c44-8b85-4bbb-a981-cea95264832f.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'Y',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-10T11:46:38.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
    {
      id: 374,
      idx: '16446f7f-e84a-4660-af4e-1be27903148e',
      activeYn: 'Y',
      deletedAt: null,
      createdAt: '2023-08-02T01:32:04.000Z',
      updatedAt: '2023-08-27T08:59:44.000Z',
      name: '한교원 매치원 유니폼',
      nameEn: 'HAN KYOWON MATCHWORN KIT',
      nameCn: 'HAN KYOWON MATCHWORN KIT',
      nameJp: 'HAN KYOWON MATCHWORN KIT',
      detailName: 'JEONBUK vs PSG - 03 AUG 2023',
      contents:
        '<pre class="ql-syntax" spellcheck="false">* 23.08.03(부산 아시아드 주경기장) 전북현대 vs 파리생제르맹 친필싸인 매치원 유니폼.\n</pre><p><strong>- AUTOGRAPH:</strong> HAN KYOWON</p><p><strong>- TYPE: </strong>MatchWorn Signed Jeonbuk Hyundai Motors 2023 Home Special Match Kit</p><p><strong>- SIGNING DATE:</strong> 06 AUG 2023</p><p><strong>- SIGNING LOCATION: </strong>Jeonju, Korea</p><p><strong>- SIZE: </strong>M</p><p><strong>- FEATURE:</strong> 03 AUG 2023 Coupang Play Series vs Paris Saint-Germain</p><p><strong>- STARTING PRICE:</strong> 250,000 WON</p><p><br></p><p>* 사이즈는 유니폼에 기재된 사이즈이며, 일부 선수(백승호,이동준,한교원,최철순,문선민)는 신체에 맞춰 리폼 후 실착하였으니 참고하시기 바랍니다.</p><p>* 유니폼은 경기 후 구단에서 가볍게 세탁 후, 싸인 세션을 진행하였습니다.</p><p>* 액자 미포함 상품으로 액자 옵션 선택 가능.</p><p><br></p><p><img src="https://image.collexx.io/17f71f52-db62-4e38-bd0c-baeab34a6798.gif"></p><p><br></p><h2>EVENT</h2><p class="ql-align-center"><a href="https://www.instagram.com/p/CvkJlshrmdN/" rel="noopener noreferrer" target="_blank" style="background-color: rgb(255, 255, 255);">이벤트 참여하기</a></p><p class="ql-align-center"><img src="https://image.collexx.io/f646c206-9ce5-4378-af21-c0bc1ef993f8.jpg"></p><p><br></p><h2>FRAMING</h2><p><br></p><p>컬렉스는 국내에서 소장 가치가 있는 수집품을 가장 멋지고 안전하게 담아내는 프레임 기술을 가지고 있습니다. 장인정신이 담긴 수작업을 통해 어떠한 데미지 없이 최고의 결과물을 보장합니다. 백여 가지의 다양한 디자인과 더불어 커스텀 맞춤 프레임까지 고객의 수집품에 맞는 솔루션을 제공합니다.<strong> </strong><a href="https://rb.gy/whcxpf" rel="noopener noreferrer" target="_blank">액자 보러가기</a></p>',
      price: 650000,
      priceEn: 490.94,
      originPrice: 250000,
      originPriceEn: null,
      deliveryCost: 0,
      discountRate: 0,
      stock: 0,
      category: 59,
      subCategory: 60,
      wishCount: 0,
      imageName: '0485cfeb-5313-4be0-bb86-8c18479a9fc4.png',
      status: 'FINISH',
      type: 'AUCTION',
      detailType: 'BASIC',
      isHotYn: 'Y',
      failCode: 'NO',
      serialNumber: null,
      startTime: '2023-08-03T15:00:00.000Z',
      deadLineTime: '2023-08-10T11:34:00.000Z',
      timeAttackHours: null,
      extendBiddingMinute: null,
      videoUrl: null,
      videoWemUrl: null,
      videoThumbnailUrl: null,
      fee: 19.8,
      offerFee: 8.8,
    },
  ];

  return new Promise(resolve => {
    resolve(data as any);
  });
}

export interface Product {
  activeYn: string;
  category: string;
  createdAt: string;
  contents?: string;
  deadLineTime: string;
  timeAttackHours: number;
  deletedAt: null;
  deliveryCost: number;
  detailName?: string;
  discountRate: number;
  id: number;
  idx: string;
  imageName: string;
  name: string;
  nameEn?: string | null;
  nameJp?: string | null;
  nameCn?: string | null;
  displayName: string;
  originPrice: number;
  originPriceEn: number;
  price: number;
  priceEn: number;
  serialNumber: null;
  status: ProductStatus;
  startTime: string | null;
  isHotYn?: YNValue;
  stock: number;
  subCategory: string;
  type: 'AUCTION' | 'BASIC';
  detailType: 'BASIC' | 'TIME' | 'SAME';
  currentCnt: number;
  limitCnt: number;
  wishCount: number;
  productHistories?: ProductionHistory[];
  productImages?: Image[];
  productTags?: Tag[];
  productOptions?: {
    createdAt: string;
    id: number;
    name: string;
    price: number;
    priceEn: number;
    stock: number;
  }[];
  videoThumbnailUrl?: string;
  videoUrl?: string;
  videoWemUrl?: string;
  updatedAt: string;

  // 제안하기 기능용
  currentOwner: CurrentOwner;
  fee: string; // 옥션, BuyNow 수수료
  offerFee: string; // 제안하기 수수료
  feeCost: number; // 옥션, 마켓 공통 결제하기용 수수료
  feeCostEn: number; // 옥션, 마켓 공통 결제하기용 수수료
}

export interface CurrentOwner {
  id: number;
  nickName: string;
  imageUrl: string;
  fee: string;
}

export type ProductStatus =
  | 'ONSALE'
  | 'FINISH'
  | 'PREPARE'
  | 'NOTUSE'
  | 'FAIL'
  | 'TIMES'
  | 'NOSTOCK';

export interface ProductionHistory {
  country: string;
  createdAt: string;
  updatedAt: string;
  id: number;
  nickName: string;
  imageUrl: string | null;
  price: number;
  priceEn: number;
}

export interface Category {
  id: number | null;
  createdAt: string;
  depth: number;
  displayOrder: number;
  name: string;
  imageUrl: string | null;
  mobileImageUrl: string | null;
  parentId: number | null;
  fee: string;
  children?: Category[];
}

export interface Tag {
  createdAt: string;
  id: number;
  name: string;
}

export interface Image {
  createdAt: string;
  id: number;
  name: string;
}

export declare type YNValue = 'Y' | 'N';
